#!/bin/sh
set -e

PARAMETERS_FILE='/var/www/html/app/config/parameters.php'

mkparameters > $PARAMETERS_FILE
chown -R www-data:www-data /var/www/html/app
chown -R www-data:www-data /var/www/html/web

cat /var/www/html/app/config/config_custom.yml

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"